### ISSUE TITLE
Hardware Availability Table

### ISSUE THREAD

**Issue by tanishqaggarwal** [pathfinder-for-autonomous-navigation/ADCSSoftware#5]
Requires resolution of #6

**Comment by kkrol27** [comment]
### HAVT Notes

Currently, there is already code in place to handle enabling and disabling devices controlled by ADCS. The subsystem update function are also written to handle this (i.e. actuating a wheel with one disabled doesn't prevent the other two from working properly, the sun sensor system can operate with fewer ADCS operational, etc.).

Each device in ADCS inherits from this `Device` class:

https://github.com/pathfinder-for-autonomous-navigation/ADCSSoftware/blob/5530b23d8dd85c30340a2f53a1086faebc4095e5/lib/Devices/Device.hpp#L24-L44

The important bits here are the `reset` and `disable` functions as well as the `is_functional` call to detect whether a device has been autonomously disabled due to failing i2c communication.

I think the following outlines a fairly crude way to proceed:

 1. Create a array of all the device pointers at compile time to allow us to assign an index to every device that's part of ADCS and easily interact with the `reset`, `disable`, and `is_functional` calls mentioned above.
 2. Expand the "command codes" defined in common software to include a `DEV_ENABLE` and `DEV_DISABLE` (or something similiar). Both of those codes would then be followed by a byte referencing a particlar device in the device pointer array that should be disabled/enabled.
 3. Complete the generation of the `HAVT` bit-array on each cycle of the ADCS. The bit-array index should match with the device pointer array indice so the `DEV_ENABLE`/`DEV_DISABLE` commands are consistant with HAVT read from the ADCS.

Obviously, the above implementation doesn't rely on a ton of abstraction and it can if we'd prefer to write it that way (as long as it works lol). I can see some lingering issue(s) with the above implementation, however, that may require a little more work to rectify:

 * Enabling a device in the middle of a control cycle could be detrimental to the ADCS' operation. For example, if an ADCS was disabled in the middle of a read operation we may not clear the input buffer and potentially disrupt devices downstream. We need a way to enable devices at a known time. I see two ways around this at the moment: cache `DEV_ENABLE` and `DEV_DISABLE` commands in a volatile data structure that's processed once every control cycle or read once at the start of a subsystem update whether a given device `is_functional` just once and cache the result. I prefer the former as it's behavior would be more predictable but increase code size unfortunately.

In general, I think the code could be broken out in a new "`dev` module" (i.e. a `src/dev.cpp` and `include/dev.hpp`) and setup at the end of the function below:

https://github.com/pathfinder-for-autonomous-navigation/ADCSSoftware/blob/5530b23d8dd85c30340a2f53a1086faebc4095e5/src/main.cpp#L47-L63

and then updated during the main control loop similar to how the other modules behave:

https://github.com/pathfinder-for-autonomous-navigation/ADCSSoftware/blob/5530b23d8dd85c30340a2f53a1086faebc4095e5/src/main.cpp#L158-L171

**Comment by shihaocao** [comment]
A quick response / todo, i will make this more legit eventually:

In nominal operation, the FC will request the ADCS HAVT table, which will respond with a bit string full of one's indicating all devices will function properly. Since all devices are functional, there is no need to send an updated command HAVT table.

the I2C command to reset or disable devices will write to an intermediate DS, which will also include an UPDATED vs OUTDATED flag to prevent commanding with stale data.

Implement update_dev() which reads from the intermediate DS
If the updated_dev() command is interrupted with the respective i2c_command, we abandon applying the intermediate DS on this cycle, and will merely attempt it next ADCS cycle.
